ARG version=9
FROM almalinux:${version}
ENV course="devops" \
    trainer="siva"
ARG duration="200 hrs"
RUN echo "hi course is ${course}, duration ${duration} and trainer is ${trainer}"
CMD [ "sleep","1000" ]
